spring:
  datasource:
    url:  jdbc:mysql://bbubbush.synology.me:22048/mission_dev_db
    username: sanghoon
    password: sanghoon12#$
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
